# Generated by Django 5.0.1 on 2024-01-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productpurchase_purchase_date_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPurchase',
        ),
    ]
