# Generated by Django 5.0.1 on 2024-01-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
