# Generated by Django 5.0.1 on 2024-01-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_userreviews_rating_rating_userreviews_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviews',
            name='ratings',
            field=models.ManyToManyField(default=0, to='product.rating'),
        ),
    ]
