# Generated by Django 5.0.1 on 2024-01-18 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_purchase_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
        ),
        migrations.AddField(
            model_name='userreviews',
            name='rating',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.rating'),
        ),
    ]
