# Generated by Django 5.0.1 on 2024-01-18 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_rating_userreviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='userreviews',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.rating'),
        ),
    ]
