# Generated by Django 5.0.1 on 2024-01-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AlterField(
            model_name='userreviews',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
