# Generated by Django 5.0.1 on 2024-01-18 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_product_rating_alter_userreviews_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreviews',
            name='rating',
        ),
    ]
