# Generated by Django 5.0.1 on 2024-01-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_userreviews_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreviews',
            name='rate',
        ),
    ]
